# Generated by Django 5.2.3 on 2025-06-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='plants/')),
                ('description', models.TextField()),
                ('therapeutic_uses', models.TextField()),
                ('active_compounds', models.TextField()),
            ],
        ),
    ]
