# Generated by Django 5.2.3 on 2025-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('smiles', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapeuticUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='active_compounds',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='therapeutic_uses',
        ),
        migrations.AddField(
            model_name='plant',
            name='active_compounds',
            field=models.ManyToManyField(blank=True, to='plants.compound'),
        ),
        migrations.AddField(
            model_name='plant',
            name='therapeutic_uses',
            field=models.ManyToManyField(blank=True, to='plants.therapeuticuse'),
        ),
    ]
