# Generated by Django 5.2.3 on 2025-06-29 13:34

import plants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_compound_therapeuticuse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='plant',
            name='active_compounds',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='therapeutic_uses',
        ),
        migrations.AlterField(
            model_name='therapeuticuse',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='active_compounds',
            field=models.TextField(blank=True, verbose_name=plants.models.Compound),
        ),
        migrations.AddField(
            model_name='plant',
            name='therapeutic_uses',
            field=models.TextField(blank=True, verbose_name=plants.models.TherapeuticUse),
        ),
    ]
