# Generated by Django 5.2.3 on 2025-06-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_compound_name_remove_plant_active_compounds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='active_compounds',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='therapeutic_uses',
            field=models.TextField(),
        ),
    ]
