# Generated by Django 5.2.3 on 2025-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_active_compounds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='active_compounds',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='therapeutic_uses',
        ),
        migrations.AddField(
            model_name='plant',
            name='active_compounds',
            field=models.ManyToManyField(blank=True, to='plants.compound'),
        ),
        migrations.AddField(
            model_name='plant',
            name='therapeutic_uses',
            field=models.ManyToManyField(blank=True, to='plants.therapeuticuse'),
        ),
    ]
