# Generated by Django 5.2.3 on 2025-06-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_remove_plant_active_compounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapeuticuse',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
